// First-launch seed. Used to populate the catalog when the app starts and no
// templates.json exists yet. Kept generic on purpose — the goal is to show
// the format and the tag picker working, not to ship anyone's real content.
import type { Template } from "./types";

const ISO = "2026-05-19T18:00:00Z";

export const starterTemplates: Template[] = [
  {
    id: "tpl-decline-meeting",
    name: "Decline meeting politely",
    tags: ["email", "decline"],
    opening: "Hi {{name}},",
    body: "Thanks for the invite — unfortunately I won't be able to make it. Happy to find another time if helpful.",
    created_at: ISO,
    updated_at: ISO,
    pinned: false,
    last_used_at: null,
    copy_count: 0,
    folder: null,
    history: [],
  },
  {
    id: "tpl-follow-up",
    name: "Follow-up after no response",
    tags: ["email", "follow-up"],
    opening: "Hi {{name}},",
    body: "Just bumping this in case it slipped past. No rush — let me know if {{topic}} is still on the table.",
    created_at: ISO,
    updated_at: ISO,
    pinned: false,
    last_used_at: null,
    copy_count: 0,
    folder: null,
    history: [],
  },
  {
    id: "tpl-quick-yes",
    name: "Quick yes to a meeting",
    tags: ["email", "accept"],
    opening: "Hi {{name}},",
    body: "Works for me. {{meeting_time}} is good — I'll send a calendar invite shortly.",
    created_at: ISO,
    updated_at: ISO,
    pinned: false,
    last_used_at: null,
    copy_count: 0,
    folder: null,
    history: [],
  },
  {
    id: "tpl-intro",
    name: "Warm intro between two people",
    tags: ["email", "intro"],
    opening: "Hi {{a}} and {{b}},",
    body: "{{a}}, meet {{b}} — {{b_oneliner}}.\n{{b}}, meet {{a}} — {{a_oneliner}}.\nI'll leave you two to take it from here.",
    created_at: ISO,
    updated_at: ISO,
    pinned: false,
    last_used_at: null,
    copy_count: 0,
    folder: null,
    history: [],
  },
  {
    id: "tpl-forum-thanks",
    name: "Forum thank-you reply",
    tags: ["forum", "thanks"],
    opening: "",
    body: "Thanks {{name}} — that fixed it. Posting the working config below for anyone hitting the same issue.",
    created_at: ISO,
    updated_at: ISO,
    pinned: false,
    last_used_at: null,
    copy_count: 0,
    folder: null,
    history: [],
  },
  {
    id: "tpl-dm-quick-ask",
    name: "Quick DM ask",
    tags: ["dm", "ask"],
    opening: "hey {{name}}",
    body: "got a sec? quick question about {{topic}} — no rush, whenever you're free.",
    created_at: ISO,
    updated_at: ISO,
    pinned: false,
    last_used_at: null,
    copy_count: 0,
    folder: null,
    history: [],
  },
];
