// One-shot: parse the project-root CSV of saved replies into src/lib/mocks.ts.
// Run: npx tsx scripts/csv-to-mocks.ts
//
// Output (src/lib/mocks.ts) is gitignored — it may contain engagement data.
// Tracked counterpart is src/lib/mocks.example.ts (small generic stub).
//
// Expects exactly one *.csv in the project root. CSV format:
//   name, created_at, updated_at, body, category, [author]
// Multi-line quoted fields and "" escapes are supported.
//
// Heuristics:
//   - Opening: first line of body if it's a bare greeting ("Hello," / "Hi," / "Hey").
//   - Signature: last non-empty line if it matches a known closer pattern.
//   - Tags: [category] if non-empty, else ["uncategorized"].

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

function findCsv(): string {
  const matches = readdirSync(root).filter((f) => f.toLowerCase().endsWith(".csv"));
  if (matches.length === 0) throw new Error("No *.csv in project root.");
  if (matches.length > 1) {
    console.warn(`Multiple CSVs found, picking first: ${matches[0]}`);
  }
  return join(root, matches[0]);
}

function parseCsv(text: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = "";
  let inQuoted = false;
  let i = 0;

  while (i < text.length) {
    const c = text[i];
    if (inQuoted) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i += 2;
          continue;
        }
        inQuoted = false;
        i++;
        continue;
      }
      field += c;
      i++;
      continue;
    }
    if (c === '"') {
      inQuoted = true;
      i++;
      continue;
    }
    if (c === ",") {
      row.push(field);
      field = "";
      i++;
      continue;
    }
    if (c === "\r") {
      i++;
      continue;
    }
    if (c === "\n") {
      row.push(field);
      rows.push(row);
      row = [];
      field = "";
      i++;
      continue;
    }
    field += c;
    i++;
  }
  if (field.length > 0 || row.length > 0) {
    row.push(field);
    rows.push(row);
  }
  return rows;
}

const GREETING_RE = /^\s*(hello|hi|hey)\b[,!.\s]*$/i;

function extractOpening(body: string): { opening: string; body: string } {
  const lines = body.split("\n");

  let opening = "";
  let start = 0;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.trim() === "") continue;
    if (GREETING_RE.test(line)) {
      opening = line.trim();
      start = i + 1;
    }
    break;
  }

  const trimmedBody = lines
    .slice(start)
    .join("\n")
    .replace(/^\s*\n+/, "")
    .replace(/\n+\s*$/, "");

  return { opening, body: trimmedBody };
}

function parseDate(raw: string): string {
  const fallback = "2026-05-19T00:00:00Z";
  const m = raw.trim().match(/^(\d{1,2})\/(\d{1,2})(?:\/(\d{2,4}))?$/);
  if (!m) return fallback;
  const day = m[1].padStart(2, "0");
  const month = m[2].padStart(2, "0");
  let year = m[3] ?? "2026";
  if (year.length === 2) year = "20" + year;
  return `${year}-${month}-${day}T00:00:00Z`;
}

function slugify(name: string, idx: number): string {
  const base = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
  return `tpl-${idx.toString().padStart(4, "0")}-${base || "untitled"}`;
}

function tsString(s: string): string {
  return JSON.stringify(s);
}

function main(): void {
  const csvPath = findCsv();
  const csv = readFileSync(csvPath, "utf8");
  const rows = parseCsv(csv);
  if (rows.length === 0) throw new Error("CSV had zero rows.");

  // Strip header.
  rows.shift();

  type Out = {
    id: string;
    name: string;
    tags: string[];
    opening: string;
    body: string;
    created_at: string;
    updated_at: string;
  };

  const out: Out[] = [];
  let skipped = 0;
  rows.forEach((cols, idx) => {
    const name = (cols[0] ?? "").trim();
    const createdRaw = cols[1] ?? "";
    const updatedRaw = cols[2] ?? "";
    const rawBody = (cols[3] ?? "").replace(/\r/g, "");
    const category = (cols[4] ?? "").trim();

    if (name === "" || rawBody.trim() === "") {
      skipped++;
      return;
    }

    const { opening, body } = extractOpening(rawBody);
    const tag = category === "" ? "uncategorized" : category.toLowerCase();

    out.push({
      id: slugify(name, idx + 1),
      name,
      tags: [tag],
      opening,
      body,
      created_at: parseDate(createdRaw),
      updated_at: parseDate(updatedRaw),
    });
  });

  const header = `// AUTO-GENERATED by scripts/csv-to-mocks.ts. Do not edit by hand.
// Regenerate after updating the project-root CSV: npx tsx scripts/csv-to-mocks.ts
import type { Template } from "./types";

export const mockTemplates: Template[] = [
`;

  const body = out
    .map(
      (t) => `  {
    id: ${tsString(t.id)},
    name: ${tsString(t.name)},
    tags: [${t.tags.map(tsString).join(", ")}],
    opening: ${tsString(t.opening)},
    body: ${tsString(t.body)},
    created_at: ${tsString(t.created_at)},
    updated_at: ${tsString(t.updated_at)},
  },`,
    )
    .join("\n");

  const footer = `\n];\n`;

  const outPath = join(root, "src", "lib", "mocks.ts");
  writeFileSync(outPath, header + body + footer, "utf8");

  console.log(
    `Wrote ${out.length} templates to ${outPath} (skipped ${skipped} empty rows).`,
  );
}

main();
